---
general:
  port: 8888
  totp_secret: '<changeme>'
  jwt_expiry: 60
  ip: '0.0.0.0'
storage:
  filesystem:
    folder: './files_basic'
    max_size: 104857600
    file_expiry: 60
exfil:
  basichttp:
    max_total_size: 104857600
    hosts:
      - 'https://my.cool.site'
  awscloudfront:
    access_key_id: '<changeme>'
    secret_access_key: '<changeme>'
    region: '<changeme>'
    distribution_tag: 'volatilevault'
    domain: my.cool.site
    folder: './files_aws'
    chunk_size: 1000000
    max_total_size: 10000000
    upload:
      mode: 'Static'
      max_duration: 5
      hosts:
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
    download:
      mode: 'Dynamic'
      max_duration: 15
      max_dynamic_hosts: 10
