---
general:
  port: 8888
  totp_secret: '<changeme>'
  jwt_expiry: 60
storage:
  filesystem:
    folder: './files_basic'
    max_size: 100
    file_expiry: 60
exfil:
  basichttp:
    max_total_size: 100
    hosts:
      - 'https://<changeme.com>'
  awscloudfront:
    access_key_id: '<changeme>'
    secret_access_key: '<changeme>'
    region: '<changeme>'
    distribution_tag: 'volatilevault'
    domain: <changeme.com>
    folder: './files_aws'
    chunk_size: 10
    max_total_size: 100 #make sure to whitelist that in your reverse proxy / server
    upload:
      mode: 'Static'
      max_duration: 5
      hosts:
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
        - '<dunno>.cloudfront.net'
    download:
      mode: 'Dynamic'
      max_duration: 15
      max_dynamic_hosts: 10
